name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Bump <?>'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - prerelease
          - prepatch
          - preminor
          - premajor
jobs:
  up-version:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Bump Version
        run: |
          git config user.name "GitHub Action"
          npm version ${{github.event.inputs.version}}
      - name: Push Version
        run: git push origin
      - name: Push Tag
        run: git push origin --tags
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
