name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version: patch or minor or major'
        required: true
        default: 'patch'

jobs:
  up-version:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checout
        uses: actions/checkout@v2
      - name: Set Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Up Version
        run: |
          git config user.name "GitHub Action"
          yarn version --${{github.event.inputs.version}}
          git push origin --tags
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
